version: '3'
services:

   nginx-rtsp:
    build: ./containers/nginx-rtsp
    image: benjaminmaynard/nginx-rtsp
    ports:
     - "80:80"
    expose:
     - "1935"
    environment:
     - CAMERA_NAME=${CAMERA_NAME}
     - AUTHORISED_USERS=${AUTHORISED_USERS}
    restart: unless-stopped

   ffmpeg:
    build: ./containers/ffmpeg
    image: benjaminmaynard/ffmpeg
    environment:
     - FRAMES_PER_SECOND=${FRAMES_PER_SECOND}
     - STREAM_WIDTH=${STREAM_WIDTH}
     - STREAM_HEIGHT=${STREAM_HEIGHT}
     - STREAM_BITRATE=${STREAM_BITRATE}
     - FLIP_HORIZONTALLY=${FLIP_HORIZONTALLY}
     - FLIP_VERTICALLY=${FLIP_VERTICALLY}
    depends_on:
     - nginx-rtsp
    devices:
     - "/dev/vchiq:/dev/vchiq"
    restart: unless-stopped